### ISSUE TITLE
Build on Android with gradle and cmake

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/mkall-java#1]

**Comment by bassosimone** [comment]
@xanscale has implemented this and he's going to submit a PR here with the changes.

**Comment by xanscale** [comment]
https://github.com/measurement-kit/mkall-java/tree/cmake

**Comment by bassosimone** [comment]
We generally close issues when they're merged in the master branch. Reopening.

**Comment by bassosimone** [comment]
All the relevant bits merged in measurement-kit/android-libs.
