### ISSUE TITLE
Allow for running integration tests on simulators

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/mkall-java#3]
(If possible, otherwise find another solution e.g. by using measurement-kit/android-example)

**Comment by bassosimone** [comment]
So, it seems this is doable by adding to the same repository both the code for generating an Android library and the code for generating a test application. At this point, we can then run the integration tests on several devices as part of said application.

**Comment by xanscale** [comment]
done with _instrumented unit tests_
https://developer.android.com/training/testing/unit-testing/instrumented-unit-tests

**Comment by bassosimone** [comment]
We generally close issues when they're merged in the master branch. Reopening.

**Comment by bassosimone** [comment]
Implemented in measurement-kit/android-libs.
